server:
  port: 8080
  shutdown: graceful
  
spring:
  application:
    name: kotlin-spring-streams
  kafka:
    application-server: ${KAFKA_APPLICATION_SERVER:localhost:8080}
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092,localhost:9093,localhost:9094}
    streams:
      application-id: kotlin-spring-streams
      properties:
        processing:
          guarantee: exactly_once_v2
        state:
          dir: ./state-dir
        
